--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KygekTeam/KygekExamplePlugin/~
build-by-default: true
branches:
- main
- pm4
projects:
  KygekExamplePlugin:
    path: ""
    libs:
    - src: KygekTeam/ktpmpl-cfs/ktpmpl-cfs
      version: ^4.0.0
...
