--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KygekTeam/KygekExamplePlugin
build-by-default: true
branches:
- main
projects:
  KygekExamplePlugin:
    path: ""
    libs:
    - src: KygekTeam/ktpmpl-cfs/ktpmpl-cfs
      version: ^1.0
    lint:
      syntaxError: false
...
